files:
  include: ['assets/**/*.scss']
rules:
    border-zero: 2
    brace-style: 2
    empty-line-between-blocks: 2
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    hex-length: 0
    indentation: 2
    leading-zero: 0
    mixins-before-declarations: 2
    nesting-depth: 0
    no-color-keywords: 0
    no-color-literals: 0
    no-css-comments: 2
    no-duplicate-properties: 0
    no-empty-rulesets: 2
    no-ids: 0
    no-important: 0
    no-misspelled-properties: 0
    no-qualifying-elements: 0
    no-trailing-whitespace: 2
    no-trailing-zero: 2
    no-transition-all: 0
    no-vendor-prefixes: 0
    one-declaration-per-line: 2
    placeholder-in-extend: 2
    property-sort-order: 0
    pseudo-element: 0
    quotes: 2
    shorthand-values: 2
    single-line-per-selector: 2
    space-after-colon: 2
    space-after-comma: 2
    space-before-bang: 0
    space-before-brace: 2
    space-before-colon: 2
    space-between-parens: 2
    trailing-semicolon: 2
